# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.5
    - CONFIG=osx_python3.6
    - CONFIG=osx_python3.7

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "aaq6ldD5yulmFn3wEruCGd/dKzDwWYOoK3rUcHrcaJvnn8XQLVK42Yk2/RjIvuvtiAa7euHnw7m+vXrJ7uOfBg1RGNK6qqkXd6Zm9ScH1HHbAiSmpWS+NzDbyQDZRvoBCl5M+gKl2UNkm9E3tjKikxR9EUXdKmpcjTz7nbd/AmwvLzvebNmtcPXtabpdv2rsXhWt8gbSPFKKc/JrqzoKfVIrd7C94p7nSXdYO5X+o7tER3/mCVhMqaVe06gO79ZnoPq6wJ2RZvbu6k9Kc1BD+OcTCQVQiZJNCgLnvI37LuApTIcILr3UEtoP+WBS0d8GUA9XV2G0pZTIoWILFdQ/STAB7raxjSalIkF0YksvqFFlzuXtCv8/MwiVLyaU8SDDS0L4hjfOXPa9tog6Ypu1ZOwfKK2gufdDTxprSFDgz48G62Pu9AF3COTrjOo11BGsCDMiNhYt4PcRQizTqSkXsXqEZozBWj7ju2zgXSpmicJOvM0ijYc2XWLCP3JQnKF6jIH6HW10Cvgi1+ALXRntIFRisIsOniI8QYkyTiZcit5770b7ts+UHFawKq79eCfxKqK6OWJ/gZlpUUFFe+kLFJeZjbI4arOvbD/QZP6/XNuLRT6LFQ4pMdY+PwhSdbxVCzJlCNPjhZJ0+flE3853lGHIj8cgl4yEAtpIFawpqI4="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install --yes --quiet conda-forge::conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml

  - conda config --remove channels defaults --force

  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml
