# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
    - CONDA_PY=35
    - CONDA_PY=36
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "brwizOr8osnlrvhRSXwfHIHebhvH+GP/r4yREMM6QtKaJx6HNGrcFrhg5wzEX+Wpqh//ai98JsqL7EVT/2ZaWOcDKaWHcoGtbgeeXj/kOYWAk2YNj6ysRg+M9OS2d6c074grMtf0b/kumKWt1HgEYbLuMMopX5LdhHFm5IrhVwCh9wYgeBMJU+3vCixfuqB5jW17JLIm8SX53KVvEdRt6T8POJ8xLtCoC29wWLhdNn4ZbKE83XlF8U0Shxaqgp1D3MUScnwKEsLlT0etYxMWfEt4s00GeWNaEMnrYVWmf8vR7K30p1Tx+YrgjaRu0lK9ZC8bX9uVqj2E4YUHVAG+cNfVBDSvVW02cIe3Gw1VcjbvXphCsVoXkpx2PpoOkO2+5dbDqz+waXRFfh49DcGOfw51IKygoZqMoeSPtUd3mDENXJwVbwGtlEwVBAJ5PmYeKe/NQHm1RLiDpKXIBpMhC8GDd1d8F6PhKArMSKLfLTdCgmtEZ83mZ1eC9Bn1PCOyfM/I/CRLnPzaNzqWJ2W19RyDp7/laNBfc8DwT9dG/djyhHR8KKZsjRU65+YUVJszKZUGUxzaG0V6b4zf0V7yk5+Ln8l/TWxVeUBH6sX9BfKdLPFYSLVLnL8XimHNYriAwLEqTkWDxCQFPGisMuIuvUDx3vFOkqD1m7ac1XlM30w="


before_install:
    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
